apiVersion: v1
kind: Service
metadata:
    labels:
        app: django-app
    name: django-app
    namespace: default
spec:
    ports:
    - name: 80-8000
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
        app: django-app
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}